theme: jekyll-theme-minimal
title: Emerald Shire Events
description: Bringing The Joy of the Shire to Your Events! Contact us today to learn how we can make your event one to remember!
layout: default
show_downloads: false
---

# Emerald Shire Events

Welcome to **Emerald Shire Events** — your premier event services partner specializing in helping game publishers and creators connect with their community. We thrive in local game store environments and bring creative energy to industry trade shows like **PAX**, **ComicCon**, and more.

## Our Services

### 🎲 Local Game Store Activations
- Organize and manage in-store gaming events
- Community outreach and engagement
- Product demo coordination

### 🏰 Trade Show Presence
- Booth setup and logistics
- Staff training and management
- Crowd engagement strategies

### 🌲 Community Building
- Ongoing support for fan communities
- Tournament planning and execution
- Online-to-offline event transition strategies

## Why Choose Us?

Emerald Shire Events is a **collaborative partner** dedicated to your success. We combine deep industry knowledge, a love for games, and a passion for community to ensure your brand thrives wherever gamers gather.

## Contact Us

Interested in working with us? Reach out at **info@emeraldshireevents.com**.

---

<style>
.wrapper > header:nth-child(1){
  display: none;
}

.wrapper > footer:nth-child(3){
  display: none;
}

body {
  background-color: #e6f2e6;
  color: #013220;
  font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
  padding: 2rem;
}

h1, h2, h3 {
  color: #005f2f;
}

a {
  color: #228b22;
}

header, footer {
  background-color: #014421;
  color: white;
  padding: 1rem;
  text-align: center;
}

main {
  max-width: 800px;
  margin: auto;
  background: #ffffff;
  padding: 2rem;
  border-radius: 8px;
  box-shadow: 0 0 10px rgba(0,0,0,0.1);
}
</style>

<footer>
  &copy; 2025 Emerald Shire Events. All rights reserved.
</footer>
